# Generated by Django 4.1 on 2024-07-21 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 10, 9, 16, 278372)),
        ),
    ]
